development:
  adapter: postgresql
  encoding: unicode
  database: BCW-DB
  pool: 5
  host: localhost
  username: bcwweb
  password: '#Bargercreek1!'
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: postgres_user_name
  password: postgres_password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 